import assert from 'node:assert/strict';
import { test } from 'node:test';
import { reportRange, parseReport, bangkokDay, shiftDay, searchPattern, csvCell, rowsCsv, deviceType, safeReferrer } from '../lib/analytics-contract.ts';
const now=new Date('2026-09-26T06:00:00Z');
const p=s=>new URLSearchParams(s);
test('default is seven calendar days in Bangkok, both dates included',()=>assert.deepEqual(reportRange(p(''),now),{start:'2026-09-20',end:'2026-09-26',from:'2026-09-19T17:00:00.000Z',until:'2026-09-26T17:00:00.000Z',days:7}));
test('UTC evening advances to next Thai calendar day',()=>assert.equal(bangkokDay(new Date('2026-09-26T17:00:00Z')),'2026-09-27'));
for(const days of [7,15,30,90])test(`preset ${days} days`,()=>assert.equal(reportRange(p(`days=${days}`),now).days,days));
test('one day has an exclusive next-midnight boundary',()=>{const r=reportRange(p('start=2026-09-26&end=2026-09-26'),now);assert.equal(r.days,1);assert.equal(Date.parse(r.until)-Date.parse(r.from),86400000);});
test('leap-day range works',()=>assert.equal(reportRange(p('start=2024-02-28&end=2024-03-01'),now).days,3));
for(const value of ['start=2026-02-30&end=2026-03-01','start=2026-09-26','start=2026-09-26&end=2026-09-25','start=2026-09-26&end=2026-09-27','start=2024-01-01&end=2026-01-01','days=999'])test(`invalid range rejected: ${value}`,()=>assert.throws(()=>reportRange(p(value),now)));
test('exactly 366 days supported',()=>assert.equal(reportRange(p('start=2024-01-01&end=2024-12-31'),now).days,366));
test('date arithmetic crosses month and year boundaries',()=>assert.equal(shiftDay('2026-01-01',-1),'2025-12-31'));
test('search wildcards are literal',()=>assert.equal(searchPattern('a%_\\b'),'%a\\%\\_\\\\b%'));
for(const value of ['=HYPERLINK("https://example.com")','  +1','\t=1','@SUM(A1)','-12'])test(`CSV formula-safe: ${JSON.stringify(value)}`,()=>assert.ok(csvCell(value).startsWith('"\'')));
test('CSV quotes, Unicode and BOM retained',()=>assert.equal(rowsCsv([{name:'ครู "เอ"'}],['name']),'\ufeff"name"\r\n"ครู ""เอ"""'));
test('defaults and pagination',()=>{const f=parseReport(p('view=users&page=2&pageSize=50'),now);assert.equal(f.page,2);assert.equal(f.provider,'all');assert.equal(f.cohort,'registered');});
for(const value of ['view=secrets','page=-1','page=1.5','pageSize=999','provider=attacker','event=payment_paid','sort=DROP TABLE users','view=users&view=payments','q='+encodeURIComponent('x'.repeat(121))])test(`invalid filter rejected: ${value.slice(0,60)}`,()=>assert.throws(()=>parseReport(p(value),now)));
test('source and subscription filters allowed',()=>assert.equal(parseReport(p('view=subscriptions&source=premium'),now).view,'subscriptions'));
test('referrer strips paths, credentials and query parameters',()=>assert.equal(safeReferrer('https://u:p@example.com/private?email=secret'),'example.com'));
test('non-HTTP referrers denied',()=>assert.equal(safeReferrer('javascript:alert(1)'),null));
test('device grouping',()=>{assert.equal(deviceType('iPad'),'tablet');assert.equal(deviceType('Android Mobile'),'mobile');assert.equal(deviceType('Macintosh'),'desktop');assert.equal(deviceType(''),'unknown');});
